<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXxAmQJ\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXxAmQJ/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEXxAmQJ.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEXxAmQJ\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerEXxAmQJ\appAppKernelDevDebugContainer([
    'container.build_hash' => 'EXxAmQJ',
    'container.build_id' => '698da88d',
    'container.build_time' => 1695732254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXxAmQJ');
