<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1HqlgD3\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1HqlgD3/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1HqlgD3.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container1HqlgD3\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container1HqlgD3\appAppKernelDevDebugContainer([
    'container.build_hash' => '1HqlgD3',
    'container.build_id' => '68b3eb0e',
    'container.build_time' => 1695839667,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1HqlgD3');
